export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_DENIED = "FETCH_PRODUCTS_DENIED";

export const SAVE_PRODUCT_REQUEST = "SAVE_PRODUCT_REQUEST";
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";
export const SAVE_PRODUCT_DENIED = "SAVE_PRODUCT_DENIED";

export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_DENIED = "DELETE_PRODUCT_DENIED";

export const FETCH_PRODUCT_BY_ID_REQUEST = "FETCH_PRODUCT_BY_ID_REQUEST";
export const FETCH_PRODUCT_BY_ID_SUCCESS = "FETCH_PRODUCT_BY_ID_SUCCESS";
export const FETCH_PRODUCT_BY_ID_DENIED = "FETCH_PRODUCT_BY_ID_DENIED";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_DENIED = "EDIT_PRODUCT_DENIED";

export const ADD_COMMENT_TO_PRODUCT_REQUEST = "ADD_COMMENT_TO_PRODUCT_REQUEST";
export const ADD_COMMENT_TO_PRODUCT_SUCCESS = "ADD_COMMENT_TO_PRODUCT_SUCCESS";
export const ADD_COMMENT_TO_PRODUCT_DENIED = "ADD_COMMENT_TO_PRODUCT_DENIED";

export const DELETE_COMMENT_FOR_PRODUCT_REQUEST = "DELETE_COMMENT_FOR_PRODUCT_REQUEST";
export const DELETE_COMMENT_FOR_PRODUCT_SUCCESS = "DELETE_COMMENT_FOR_PRODUCT_SUCCESS";
export const DELETE_COMMENT_FOR_PRODUCT_DENIED = "DELETE_COMMENT_FOR_PRODUCT_DENIED";

export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_DENIED = "FETCH_COMMENTS_DENIED";


export const SORT_PRODUCTS_BY_ALPHABET = "SORT_PRODUCTS_BY_ALPHABET";
export const SORT_PRODUCTS_BY_COUNT = "SORT_PRODUCTS_BY_COUNT";


export const HIDE_CONFIRMATION_MODAL = "HIDE_CONFIRMATION_MODAL";

