export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_DENIED = "FETCH_PRODUCTS_DENIED";

export const SAVE_PRODUCT_REQUEST = "SAVE_PRODUCT_REQUEST";
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";
export const SAVE_PRODUCT_DENIED = "SAVE_PRODUCT_DENIED";

export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_DENIED = "DELETE_PRODUCT_DENIED";

export const FETCH_PRODUCT_BY_ID_REQUEST = "FETCH_PRODUCT_BY_ID_REQUEST";
export const FETCH_PRODUCT_BY_ID_SUCCESS = "FETCH_PRODUCT_BY_ID_SUCCESS";
export const FETCH_PRODUCT_BY_ID_DENIED = "FETCH_PRODUCT_BY_ID_DENIED";

export const HIDE_CONFIRMATION_MODAL = "HIDE_CONFIRMATION_MODAL";

